### ISSUE TITLE
Message parser chokes on actual payload lengths that don't match ideal lengths defined by common.xml

### ISSUE THREAD

**Issue by tstellanova** [tstellanova/rust-mavlink#2]
Actual payload length can vary from "theoretical" in MAVLink.   When px4_sitl sends MAV_CMD_SET_MESSAGE_INTERVAL , the payload is truncated to 30 bytes instead of 33

Written by px4_sitl:
```
read H: [30, 0, 0, 0, 0, 50, 76, 0, 0] header_len: 9 
```
Written by rust-mavlink:
```
read H: [33, 0, 0, 239, 1, 1, 76, 0, 0] header_len: 9 
```

**Comment by tstellanova** [comment]
The root cause seems to be that  the message `deser` tries to read more bytes than are actually available in the buffer, in the case where payloads are truncated.    

jMAVSim works around this empty field truncation in MAVLinkMessageDefinition() by summing the size of all fields into a payloadLength and storing it with the message definition. 
cc @podhrmic

**Comment by podhrmic** [comment]
Good point. The [mavlink guide](https://mavlink.io/en/guide/serialization.html#payload_truncation) describes the truncation, I just haven't implemented it. I am happy to add it to my TODO list, unless you need it very soon?

**Comment by tstellanova** [comment]
fixed in latest master
